### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by hemangsk** [viper-development/viper-development.github.io#11]
Milestones: 
[Mockup](https://app.moqups.com/hemangsk@gmail.com/aYpkl6Xx0r/)

Hey! here are the features we're working on to integrate in the viperdev website. Please let us know what you think.

- [x] To create the basic structure using a material design centric approach, with all the components in the mockup converted to their material design counterparts

- [ ]  An about us page, as in mockup, to show [OpenHUB stats](https://github.com/viper-development/viper-development.github.io/issues/4), [Showcase work](https://github.com/viper-development/viper-development.github.io/issues/5) and more analytics focussed content.

- [x]  Font centric approach : Uniform font Roboto with its weight variations throughout the site.  

- [x]  'Catch us today' Page : To announce upcoming workshops and events

- [x]  [Impressum](https://github.com/viper-development/viper-development.github.io/issues/8), social links to go in the footer

- [ ]  Add pictures of workshops in the About Us page

- [x]  Gitter embed. Already there in the existing site

- [x]  Nav links + Mail Us Section in the footer. 

- [x]  Google Analytics

- [x]  Carousel for quotes and Testimonials

- [x]  Personalised short bio for about us page

- [ ]  Categorise services and price quotes

- [x]  "Let us do it" Page : Show specific offers on site [Ideas](https://docs.google.com/presentation/d/1KJSKHJKQKvZnRHfEUb1ZBnuaAtj9RgBwqS7Wrv1DATM/edit?usp=sharing)
  
**CHANGELOG**
- [ ] For the team: Let's have the same kind of picture Lasse has for everyone and a custom bio. Don't get picture and text from github, we need some more professional stuff here. Maybe add a sentence that "those are our contractors that are working towards your needs" or something.

- [x]  To improve titles, they're not too helpful in figuring out what to find there.

Track the WIP at : https://github.com/hemangsk/viperdev-site

**Comment by sils** [comment]
what's the map for?

**Comment by sils** [comment]
Idea: add google analytics

**Comment by sils** [comment]
Idea: use a carousel for the quotes, the number of good quotes is raising, maybe clickable to get the full list or something, not sure.

**Comment by sils** [comment]
Idea: maybe add some description or a tagline for every "member"? Maybe call it "the team" or so. Makes the whole thing more personal.

**Comment by hemangsk** [comment]
Google Map for - like the address of viperdev office, if anyone wants to have a meeting to discuss project

**Comment by sils** [comment]
we don't have an office.

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala.io/ - http://viperdev.io/ - http://gitmate.com/

**Comment by sils** [comment]
we'd usually do meetings via skype/hangouts or fly in to the client for any
bigger project.

I'm actually potentially moving to a new flat soon and if that works out
I'll certainly think about some meeting space in my office though it sounds
so decadent.

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala.io/ - http://viperdev.io/ - http://gitmate.com/

**Comment by seblat** [comment]
Just a real quick draft on what we started talking about at telegram a few hours ago:

https://docs.google.com/presentation/d/1KJSKHJKQKvZnRHfEUb1ZBnuaAtj9RgBwqS7Wrv1DATM/edit?usp=sharing

So the idea is to offer certain solution instead of just general software development skills. since usually people are looking for solutions ;)
The 3 solution above are just ideas and open for discussion.

Ive seen you updatet the homepage more towards code quality already or has it always been like this?

**Comment by hemangsk** [comment]
That's a great add on.. we can have a kind of "Let us solve it" page.. consisting of all the specific solutions points, organised in a real cool manner, maybe like a flow graph or a use case diagram i think

**Comment by sils** [comment]
nice, long term I can see that page growing into a list of actual products
maybe even with actual price tags. Selling products vs. selling hours.

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala.io/ - http://viperdev.io/ - http://gitmate.com/

**Comment by hemangsk** [comment]
Hey! these materials are needed for the website.. 
- [ ] picture of workshops to put in the About Us page
- [ ] services and price quotes which'll go in "Request a Quote" Page

I think having workshop pictures will have a nice impact.

**Comment by sils** [comment]
@hemangsk go with what @seblat sent for the services and don't put price tags on it for now, still kinda hard to tell :/

I searched for workshop pictures, didn't find any so far...

**Comment by hemangsk** [comment]
Thanks.. Okay I'm on it 👍  😄

**Comment by sils** [comment]
- [ ] For the team: let's have the same kind of picture I have for everyone and a custom text? Don't get picture and text from github, we need some more professional stuff here. Also add yourself. Maybe add a sentence that "those are our contractors that are working towards your needs" or something

**Comment by sils** [comment]
- [ ] improve titles, they're not too helpful in figuring out what to find there

**Comment by hemangsk** [comment]
Hey lets change,
"Dive into Viperdev" title to -> "About Us"
& "About Us" -> "Meet the Team"
sounds more apt

**Comment by sils** [comment]
Most of what is here discussed has been implemented, let us track further improvements in own issues.
