### ISSUE TITLE
Add separation between title and description

### ISSUE THREAD

**Issue by aptrishu** [viper-development/viper-development.github.io#27]
![vpdv](https://cloud.githubusercontent.com/assets/22702242/21550318/c8cef2c8-ce1e-11e6-9a78-7aa677b70eca.png)

Here also I think some work on fonts is required
the font weight and colour separation is nice but the title and description below it doesn't look distinct/distinguishable.
A sharp underline or increasing font weight or including a little separation in between can work.
Also make the same changes to other such sections.

**Comment by aptrishu** [comment]
CC @hemangsk

**Comment by hemangsk** [comment]
Hey! Thanks for reporting this one! Yeah looks like a line break will increase readability here. 😄

**Comment by aptrishu** [comment]
so, You're making the PR or should I ? :P

**Comment by hemangsk** [comment]
Sure please go ahead, that'll awesome, let me assign you
