### ISSUE TITLE
coafile

### ISSUE THREAD

**Issue by hemangsk** [viper-development/viper-development.github.io#30]
This is for some discussion on the `coafile`. because,   [the PR thread](https://github.com/viper-development/viper-development.github.io/pull/26) has got too long 😅 😿  

Can we go with this coafile,
```
[default]
bears = LineCountBear, FilenameBear, InvalidLinkBear, coalaBear
files = **.md, **.html, **.js, **.css, **.yml
ignore = **.min.(css|js), _site/**.(html|js|css)
max_lines_per_file = 600

[markdown]
bears = MarkdownBear, SpaceConsistencyBear, KeywordBear
files = **.md
language = markdown
use_spaces = yes

[yaml]
bears = YAMLLintBear, SpaceConsistencyBear, LineLengthBear, KeywordBear
files = **.yml
language = YAML
use_spaces = yes

[javascript]
bears = JSComplexityBear
files = **.js
ignore = _site/**.js

[html]
bears = HTMLLintBear, BootLintBear, SpaceConsistencyBear, KeywordBear
files = **.html
ignore = _site/**.html, _includes/github.html
language = HTML
use_spaces = yeah

[css]
bears = SpaceConsistencyBear
files = **.css
ignore = _site/**.css, **.min.css
use_spaces = yes
```

Log of modifications, 
- Minified css and js files, added in [css] and [js] sections
- Ignore `site` folder completely 
- CSSLintBear is posing some problems,
  - It doesn't allow more than 10 `!important`, but if !important is removed, some default bootstrap and materialize styles won't be overridden.
  - CSSLintBear's Ignore Action is not working as its supposed to, I'll start fixing it ASAP, [opened an issue too](https://github.com/coala/coala-bears/issues/1225)

**Comment by sils** [comment]
> It doesn't allow more than 10 !important, but if !important is removed, some default bootstrap and materialize styles won't be overridden.

Can you just disable that? Is there a setting for that? If not we should patch CSSLintBear

**Comment by hemangsk** [comment]
In #26 , all our code is now coala compliant
can we merge this one or we should wait for the `IgnoreResultAction` patch?

**Comment by sils** [comment]
no we shouldn't, we can manually add ignore comments if ignoreresultaction doesn't work right?

**Comment by hemangsk** [comment]
I tried it, Its ignoring the ignore comments written manually.

This doesn't seem to work,
```
/*  # Ignore CSSLintBear   */
```
