### ISSUE TITLE
readme screenshot is out of date

### ISSUE THREAD

**Issue by sils** [viper-development/viper-development.github.io#73]
@hemangsk how did you create it anyway?

**Comment by hemangsk** [comment]
For Desktop : -
A screenshot of whole Chrome window using Cmd + Shift + 4 + Space

For Mobile : - 
Clicked screenshot from mobile and used this - https://developer.android.com/distribute/tools/promote/device-art.html# This is really awesome tool, it wraps the screenshot in the device of our choice and generates an image with shadow effect.

Then combined this desktop and mobile screenshot in photoshop

**Comment by sils** [comment]
sounds like a lot of work, maybe just remove it :)

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala.io/ - http://viperdev.io/ - http://gitmate.com/
